language: java
jdk:
- oraclejdk8
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=indrabasak-github
  -Dsonar.login=$SONAR_TOKEN
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
env:
  global:
    secure: gB+Fet79DyCHPG035qNmhi621NC0OgDtY5mav/FkYMOEvSxEcySR8q0246CEqfZHwnFw8Fj3UJEb3rR6DwGUswwTxrD2m4uCiIIZYzTtyy6dYkVSAW2q7S5pFga+8QUXJpTUCcn8Z/QlAZunSDY+GCnkUhQSxsh2gYxqZ/ZqZJtDBUhRFWIfIFEmACh4Ix8QfTNlNAcvtBZQQzEfHfw8lVNAMW0Zn/vsEv2eQ4z6gl1nTvLiXvquawML0dGdyJoSJcuhu3znz9AekBV4oIyUyDYBL40X8QS6FgAtGMwAvwhAD2h0RliucF/3dLz5JPSjneTX2SBDWhi5oWcAHYQ7RMGvMKa/TVKIVxmg1O9r3p6Y9qwnPVYjQOozg4aT0eKVCxGlhdEFnJntez88Jvod8kza2lnM1nmlhDo1y476cWilSWWcLw70ZQv30S4n+YEfYcP+8J7PD4eShQ8PBDs4EaKPFa+9mxkmc6AEqR0K6KMqYmu3VBykvZPgLH/Leqa2SiPnxImbIeAUL5SETLUrmHVHsJWhT7o4suAmvzALYywqNLQiS5/4MS0AGbMCHk3Rxd1SZ70CM+PWhuaIH3fmk/ciDU8dtqFLftGos23e7gmVnKF0nbchpSvZtYGfOCLuzEfEqaky/E2Hj2wvdlJ0Sg2SGj1Wi7aSPcffIkLJN8A=
